[versions]
androidGradlePlugin = "8.13.2"
jetbrainsKotlin = "2.3.0"
androidxRoom = "2.8.4"
mikepenzAboutLibraries = '10.6.1'
androidxCompose = '1.10.0'
googleDaggerHilt = "2.57.2"
androidxHiltNavigationCompose = "1.3.0"
androidxDatastorePreferences = "1.2.0"
androidxAppcompat = "1.7.1"
androidxLifecycleRuntime = "2.10.0"
androidxCoreKtx = "1.17.0"
androidxActivityCompose = "1.12.2"
androidxComposeMaterialIconsExtended = "1.7.8"
androidxComposeMaterial3 = "1.4.0"
googleAccompanistPager = "0.28.0"
googleAccompanistSystemuicontroller = "0.28.0"
googleDevtoolsKsp = "2.3.4"
raamcostaComposeDestinations = "1.11.6"
jetbrainsKotlinxSerializationJson = "1.9.0"
androidxDocumentFile = "1.0.1"
androidxWorkRuntime = "2.11.0"
androidxHiltWork = "1.2.0"
androidxHilt = "1.2.0"
materialKolor = "2.0.0"
junit = "4.13.2"
androidxTestExtJunit = "1.2.1"
androidxTestEspressoCore = "3.6.1"
androidxComposeFoundation = "1.10.0"
androidxGraphicsShape = "1.1.0"
squareupOkhttp3 = "5.0.0-alpha.14"
jeziellagoComposeMarkdown = "0.5.4"
androidToolsDesugarJdkLibs = "2.1.5"

compileSdk = "36"
minSdk = "24"
targetSdk = "36"

[libraries]
# Android App
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-documentFile = { group = "androidx.documentfile", name = "documentfile", version.ref = "androidxDocumentFile" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycleRuntime" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycleRuntime" }

# Compose
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidxCompose" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "androidxCompose" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "androidxCompose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidxCompose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidxCompose" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidxCompose" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "androidxCompose" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "androidxComposeMaterialIconsExtended" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation-android", version.ref = "androidxComposeFoundation" }
androidx-graphics-shape = { group = "androidx.graphics", name = "graphics-shapes", version.ref = "androidxGraphicsShape" }
raamcosta-compose-destinations = { group = "io.github.raamcosta.compose-destinations", name = "animations-core", version.ref = "raamcostaComposeDestinations" }
raamcosta-compose-destinations-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "raamcostaComposeDestinations" }
google-accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "googleAccompanistPager" }
google-accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "googleAccompanistSystemuicontroller" }

# Tests
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxTestEspressoCore" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

# DI Hilt
google-dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "googleDaggerHilt" }
google-dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "googleDaggerHilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "androidxHilt" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidxHilt" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidxHiltWork" }

# Database
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }

# DataStore
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastorePreferences" }

# Network
squareup-okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "squareupOkhttp3" }

# WorkManager
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWorkRuntime" }

# Kotlin
jetbrains-kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "jetbrainsKotlinxSerializationJson" }

# Other
mikepenz-aboutLibraries-compose = { group = "com.mikepenz", name = "aboutlibraries-compose", version.ref = "mikepenzAboutLibraries" }
jeziellago-compose-markdown = { group = "com.github.jeziellago", name = "compose-markdown", version.ref = "jeziellagoComposeMarkdown" }
materialKolor-material-kolor = { group = "com.materialkolor", name = "material-kolor", version.ref = "materialKolor" }
android-tools-desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidToolsDesugarJdkLibs" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrainsKotlin" }
google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "googleDaggerHilt" }
mikepenz-aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "mikepenzAboutLibraries" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "googleDevtoolsKsp" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "jetbrainsKotlin" }
jetbrains-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "jetbrainsKotlin" }