[versions]
androidGradlePlugin = "8.13.2"
androidToolsDesugarJdkLibs = "2.1.5"
androidxActivityCompose = "1.12.2"
androidxAppcompat = "1.7.1"
androidxCompose = '1.10.0'
androidxComposeMaterial3 = "1.4.0"
androidxComposeMaterialIconsExtended = "1.7.8"
androidxCoreKtx = "1.17.0"
androidxDatastorePreferences = "1.2.0"
androidxDocumentFile = "1.0.1"
androidxGraphicsShape = "1.1.0"
androidxHilt = "1.2.0"
androidxHiltNavigationCompose = "1.3.0"
androidxHiltWork = "1.2.0"
androidxLifecycleRuntime = "2.10.0"
androidxRoom = "2.8.4"
androidxWorkRuntime = "2.11.0"
googleAccompanistPager = "0.28.0"
googleAccompanistSystemuicontroller = "0.28.0"
googleDaggerHilt = "2.57.2"
googleDevtoolsKsp = "2.3.4"
jetbrainsKotlin = "2.3.0"
jetbrainsKotlinxSerializationJson = "1.9.0"
jeziellagoComposeMarkdown = "0.5.4"
junit = "4.13.2"
materialKolor = "2.0.0"
mikepenzAboutLibraries = '13.2.1'
raamcostaComposeDestinations = "1.11.6"
squareupOkhttp3 = "5.0.0-alpha.14"

# Sdk versions
compileSdk = "36"
minSdk = "24"
targetSdk = "36"

[libraries]
# AndroidX
android-tools-desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidToolsDesugarJdkLibs" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "androidxComposeMaterialIconsExtended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidxCompose" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "androidxCompose" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidxCompose" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidxCompose" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidxCompose" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "androidxCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastorePreferences" }
androidx-documentFile = { group = "androidx.documentfile", name = "documentfile", version.ref = "androidxDocumentFile" }
androidx-graphics-shape = { group = "androidx.graphics", name = "graphics-shapes", version.ref = "androidxGraphicsShape" }
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "androidxHilt" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidxHilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidxHiltWork" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycleRuntime" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycleRuntime" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWorkRuntime" }

# Google
google-accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "googleAccompanistPager" }
google-accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "googleAccompanistSystemuicontroller" }
google-dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "googleDaggerHilt" }
google-dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "googleDaggerHilt" }

# JetBrains
jetbrains-kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "jetbrainsKotlinxSerializationJson" }

# Third Party
jeziellago-compose-markdown = { group = "com.github.jeziellago", name = "compose-markdown", version.ref = "jeziellagoComposeMarkdown" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
materialKolor-material-kolor = { group = "com.materialkolor", name = "material-kolor", version.ref = "materialKolor" }
mikepenz-aboutLibraries-compose = { group = "com.mikepenz", name = "aboutlibraries-compose", version.ref = "mikepenzAboutLibraries" }
raamcosta-compose-destinations = { group = "io.github.raamcosta.compose-destinations", name = "animations-core", version.ref = "raamcostaComposeDestinations" }
raamcosta-compose-destinations-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "raamcostaComposeDestinations" }
squareup-okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "squareupOkhttp3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "googleDaggerHilt" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "googleDevtoolsKsp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrainsKotlin" }
jetbrains-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "jetbrainsKotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "jetbrainsKotlin" }
mikepenz-aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "mikepenzAboutLibraries" }